#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x8FE99503132D7742 (antonio@gnu.org)
#
Name     : lzlib
Version  : 1.9
Release  : 1
URL      : http://download.savannah.gnu.org/releases/lzip/lzlib/lzlib-1.9.tar.gz
Source0  : http://download.savannah.gnu.org/releases/lzip/lzlib/lzlib-1.9.tar.gz
Source99 : http://download.savannah.gnu.org/releases/lzip/lzlib/lzlib-1.9.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: lzlib-lib = %{version}-%{release}
Requires: lzlib-license = %{version}-%{release}

%description
Description
Lzlib is a data compression library providing in-memory LZMA compression
and decompression functions, including integrity checking of the
decompressed data. The compressed data format used by the library is the
lzip format. Lzlib is written in C.

%package dev
Summary: dev components for the lzlib package.
Group: Development
Requires: lzlib-lib = %{version}-%{release}
Provides: lzlib-devel = %{version}-%{release}

%description dev
dev components for the lzlib package.


%package doc
Summary: doc components for the lzlib package.
Group: Documentation

%description doc
doc components for the lzlib package.


%package lib
Summary: lib components for the lzlib package.
Group: Libraries
Requires: lzlib-license = %{version}-%{release}

%description lib
lib components for the lzlib package.


%package license
Summary: license components for the lzlib package.
Group: Default

%description license
license components for the lzlib package.


%prep
%setup -q -n lzlib-1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547099087
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1547099087
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lzlib
cp COPYING.GPL %{buildroot}/usr/share/package-licenses/lzlib/COPYING.GPL
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/liblz.so

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/info/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblz.so.1
/usr/lib64/liblz.so.1.9

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lzlib/COPYING.GPL
